name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-go-dep-${{ hashFiles('**/yarn.lock') }}
      - name: dependencies
        run: yarn install
      - name: build
        run: |
          yarn build
      - name: deploy
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./public
          external_repository: testforme-io/site-generated
          publish_branch: main
